---
- name: install dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - make

- name: Upload required scripts
  loop: 
    - fetch_feeds.sh
    - generate_custom_ioc_rules.py
    - Makefile
    - update_rules.sh
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ username }}/{{ item }}"
    mode: "0755"
    owner: "{{ username }}"
    group: "{{ username }}"
